version: '3.8'

services:

    nodejs_service:
        build: 
            context: ./nodejs
            dockerfile: DockerFile
        networks: 
            - webservice
        ports: 
            - 3000:3000
        depends_on: 
            - database_mysql  

    php_service:
        build: 
            context: ./php
            dockerfile: DockerFile
        networks: 
            - webservice
        depends_on: 
            - database_mysql  
    
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx:/etc/nginx/conf.d
        networks:
            - webservice
        depends_on: 
            - php_service  
    
    database_mysql: 
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: 'example'
            MYSQL_ROOT_PASSWORD: 'password1'
        networks:
            - webservice

networks:
    webservice: